version: "3.5"

services:

  mysql-db:
    image: mysql:5.7.10
    container_name: mysql-db
    ports:
      - 3306:3306
    volumes:
      - ../config/mysql:/data/application
      - ./mysql-data:/var/lib/mysql
    networks:
      - prepaid-data-network
    environment:
      - MYSQL_ROOT_HOST='%'
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    restart: unless-stopped
    command: --init-file=/data/application/init.sql

  my-rabitmq:
    image: rabbitmq:management
    container_name: my-rabitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - prepaid-data-network
    restart: unless-stopped

  voucher:
    image: ghcr.io/longnguyencse/purchase-prepaid-data/voucher:${VOUCHER_SERVICE_VERSION}
    container_name: voucher
    ports:
      - 8081:8080
    networks:
      - prepaid-data-network
    restart: unless-stopped
    environment:
      - PROFILE=${VOUCHER_SERVICE_PROFILE}
      - PORT=${INSTANT_PORT}

#  prepaid-data:
#    image: ghcr.io/longnguyencse/purchase-prepaid-data/core-prepaid-data:${CORE_PREPAID_VERSION}
#    container_name: prepaid-data
#    depends_on:
#      - mysql-db
#      - my-rabitmq
#    ports:
#      - 9192:8080
#    networks:
#      - prepaid-data-network
#    restart: unless-stopped
#    environment:
#      - PORT=${INSTANT_PORT}
#      - PROFILE=${CORE_PREPAID_PROFILE}
#      - DB_USER=${DB_USER}
#      - DB_PASSWORD=${DB_PASSWORD}
#      - DB_HOST=${DB_HOST}
#      - DB_PORT=${DB_PORT}
#      - DB_NAME=${DB_NAME}
#      - DB_MAX_POOL=${DB_MAX_POOL}
#      - VOUCHER_SERVER_URL=${VOUCHER_SERVER_URL}
#      - SECRET_KEY=${SECRET_KEY}
#      - TIMEOUT_SEND_SMS=${TIMEOUT_SEND_SMS}
#      - RABBITMQ_QUEUE=${RABBITMQ_QUEUE}
#      - RABBITMQ_EXCHANGE=${RABBITMQ_EXCHANGE}
#      - RABBITMQ_ROUTING_KEY=${RABBITMQ_ROUTING_KEY}
#      - RABBITMQ_HOST=${RABBITMQ_HOST}
#      - RABBITMQ_PORT=${RABBITMQ_PORT}
#      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
#      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}

  notification:
    image: ghcr.io/longnguyencse/purchase-prepaid-data/notification:${NOTIFICATION_VERSION}
    container_name: notification
    depends_on:
      - my-rabitmq
    ports:
      - 9193:8080
    networks:
      - prepaid-data-network
    restart: unless-stopped
    environment:
      - PORT=${INSTANT_PORT}
      - PROFILE=${NOTIFICATION_PROFILE}
      - RABBITMQ_QUEUE=${RABBITMQ_QUEUE}
      - RABBITMQ_EXCHANGE=${RABBITMQ_EXCHANGE}
      - RABBITMQ_ROUTING_KEY=${RABBITMQ_ROUTING_KEY}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}

networks:
  prepaid-data-network:
    name: jprepaid-data-network
    driver: bridge