version: "3.5"

services:

  mysql-db:
    image: mysql:5.7.10
    container_name: mysql-db
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - prepaid-data-network
    environment:
      - MYSQL_ROOT_HOST='%'
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    restart: unless-stopped

  my-rabitmq:
    image: rabbitmq:management
    container_name: my-rabitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - prepaid-data-network
    restart: unless-stopped

  voucher:
    image: ghcr.io/longnguyencse/purchase-prepaid-data/voucher:${VOUCHER_SERVICE_VERSION}
    container_name: voucher
    ports:
      - 8081:8080
    networks:
      - prepaid-data-network
    restart: unless-stopped
    environment:
      - PROFILE: ${VOUCHER_SERVICE_PROFILE}
      - PORT: ${INSTANT_PORT}

  prepaid-data:
    image: ghcr.io/longnguyencse/purchase-prepaid-data/core-prepaid-data:${CORE_PREPAID_VERSION}
    container_name: prepaid-data
    depends_on:
      - mysql-db
      - my-rabitmq
    ports:
      - 9192:8080
    networks:
      - prepaid-data-network
    restart: unless-stopped
    environment:
      - PROFILE: ${CORE_PREPAID_PROFILE}
      - DB_USER: ${DB_USER}
      - DB_PASSWORD: ${DB_PASSWORD}
      - DB_HOST: ${DB_HOST}
      - DB_PORT: ${DB_PORT}
      - DB_NAME: ${DB_NAME}
      - DB_MAX_POOL: ${DB_MAX_POOL}
      - VOUCHER.SERVER.URL: ${VOUCHER.SERVER.URL}
      - SECRET_KEY: ${SECRET_KEY}
      - TIMEOUT.SEND.SMS: ${TIMEOUT.SEND.SMS}
      - RABBITMQ.QUEUE: ${RABBITMQ.QUEUE}
      - RABBITMQ.EXCHANGE: ${RABBITMQ.EXCHANGE}
      - RABBITMQ.ROUTING_KEY: ${RABBITMQ.ROUTING_KEY}
      - RABBITMQ.HOST: ${RABBITMQ.HOST}
      - RABBITMQ.PORT: ${RABBITMQ.PORT}
      - RABBITMQ.USERNAME: ${RABBITMQ.USERNAME}
      - RABBITMQ.PASSWORD: ${RABBITMQ.PASSWORD}

  notification:
    image: ghcr.io/longnguyencse/purchase-prepaid-data/notification:${NOTIFICATION_VERSION}
    container_name: notification
    depends_on:
      - my-rabitmq
    ports:
      - 9193:8080
    networks:
      - prepaid-data-network
    restart: unless-stopped
    environment:
      - PROFILE: ${NOTIFICATION_PROFILE}
      - RABBITMQ.QUEUE: ${RABBITMQ.QUEUE}
      - RABBITMQ.EXCHANGE: ${RABBITMQ.EXCHANGE}
      - RABBITMQ.ROUTING_KEY: ${RABBITMQ.ROUTING_KEY}
      - RABBITMQ.HOST: ${RABBITMQ.HOST}
      - RABBITMQ.PORT: ${RABBITMQ.PORT}
      - RABBITMQ.USERNAME: ${RABBITMQ.USERNAME}
      - RABBITMQ.PASSWORD: ${RABBITMQ.PASSWORD}

networks:
  prepaid-data-network:
    name: jprepaid-data-network
    driver: bridge