# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: build jio-bff-mobile qa

on:
  push:
    branches: [ sit/** ]
    paths:
      - 'backend/voucher/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Grant execute permission for gradlew
        working-directory: backend/jio-bff-mobile
      - name: Build Docker image
        run: ./build_docker.sh qa
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
        working-directory: backend/voucher
